#!/bin/sh
set -eu

: "${MARIADB_WAYFARER_USER:?MARIADB_WAYFARER_USER is required}"
: "${MARIADB_WAYFARER_PASSWORD:?MARIADB_WAYFARER_PASSWORD is required}"

mariadb --protocol=socket -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS wayfarer_luckperms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wayfarer_mcmmo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wayfarer_network CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MARIADB_WAYFARER_USER}'@'%' IDENTIFIED BY '${MARIADB_WAYFARER_PASSWORD}';
GRANT ALL PRIVILEGES ON wayfarer_luckperms.* TO '${MARIADB_WAYFARER_USER}'@'%';
GRANT ALL PRIVILEGES ON wayfarer_mcmmo.* TO '${MARIADB_WAYFARER_USER}'@'%';
GRANT ALL PRIVILEGES ON wayfarer_network.* TO '${MARIADB_WAYFARER_USER}'@'%';
FLUSH PRIVILEGES;
SQL
