#!/bin/sh
set -eu

: "${MARIADB_WAYFARER_USER:?MARIADB_WAYFARER_USER is required}"
: "${MARIADB_WAYFARER_PASSWORD:?MARIADB_WAYFARER_PASSWORD is required}"
: "${MARIADB_EVENMOREFISH_USER:?MARIADB_EVENMOREFISH_USER is required}"
: "${MARIADB_EVENMOREFISH_PASSWORD:?MARIADB_EVENMOREFISH_PASSWORD is required}"

mariadb --protocol=socket -uroot -p"${MARIADB_ROOT_PASSWORD}" <<SQL
CREATE DATABASE IF NOT EXISTS wayfarer_luckperms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wayfarer_mcmmo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wayfarer_network CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS wayfarer_evenmorefish CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${MARIADB_WAYFARER_USER}'@'%' IDENTIFIED BY '${MARIADB_WAYFARER_PASSWORD}';
CREATE USER IF NOT EXISTS '${MARIADB_EVENMOREFISH_USER}'@'%' IDENTIFIED BY '${MARIADB_EVENMOREFISH_PASSWORD}';
GRANT ALL PRIVILEGES ON wayfarer_luckperms.* TO '${MARIADB_WAYFARER_USER}'@'%';
GRANT ALL PRIVILEGES ON wayfarer_mcmmo.* TO '${MARIADB_WAYFARER_USER}'@'%';
GRANT ALL PRIVILEGES ON wayfarer_network.* TO '${MARIADB_WAYFARER_USER}'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, DROP, REFERENCES ON wayfarer_evenmorefish.* TO '${MARIADB_EVENMOREFISH_USER}'@'%';
FLUSH PRIVILEGES;
SQL
